defaults:
  - default
  - agent: ???
  - buffer: ??? 
  - envs: car_racing
  - vae: ???
  
max_episodes: 1000
max_steps: 1000
batch_size: 128
num_eval_episodes: 1
eval_interval: 10
reconstructed_log_interval: 100
record_video: True

save_ckpt_dir: ???
